import 'dart:convert';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:image_picker/image_picker.dart';
import 'package:keluarga_bintoro/models/project_model.dart';
import 'package:keluarga_bintoro/models/schedule_model.dart';
import 'package:keluarga_bintoro/services/project_service.dart';
import 'package:keluarga_bintoro/shared/functions.dart';
import 'package:keluarga_bintoro/shared/shared_endpoint.dart';
import 'package:keluarga_bintoro/ui/widgets/widgets.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
part 'sign_in_page.dart';
part 'home_page.dart';
part 'daily_report.dart';
part 'project_page.dart';
part 'quality_control_page.dart';
part 'landing_page.dart';
part 'list_project_page.dart';
